### ISSUE TITLE
Python bindings?

### ISSUE THREAD

**Issue by Le0Developer** [null8626/decancer#1]
## Is your feature request related to a problem?

There currently aren't any good libraries for decancering text in python.

## Describe the solution you'd like

I'd like python bindings using a lib such as [PyO3](https://github.com/PyO3/PyO3).

## Describe alternatives you've considered

I tried reinventing the wheel but failed and would love to integrate this perfectly working library into my python projects as well.

**Comment by Le0Developer** [comment]
Thank you [kind soul](https://github.com/Jonxslays/decancer_py).

**Comment by null8626** [comment]
Interesting! I'll add this third-party binding to the README!
