### ISSUE TITLE
The character "Æ" (U+00C6) appears to cause cure to panic.

### ISSUE THREAD

**Issue by Yossipossi1** [null8626/decancer#12]
Not sure why this is the case. Happens on version 1.6.2 in Rust with the error `attempt to subtract with overflow`, error location being `src/lib.rs:95:20`. This also occurs with `cure_char()`.

**Comment by null8626** [comment]
Hi! Thanks for reporting this bug. Will look into it!

**Comment by null8626** [comment]
This issue is now fixed! Now wait for the future release of `v1.6.3` to ship with this bugfix! Thank you for reporting! ❤️
