### ISSUE TITLE
Remove usage of `unsafe` completely

### ISSUE THREAD

**Issue by Milo123459** [null8626/decancer#20]
There is no reason for this crate to use `unsafe` code.

**Comment by null8626** [comment]
Would this be possible though? Because the crate also reads from a custom-made binary - which wouldn't be possible without some pointer arithmetic.

**Comment by null8626** [comment]
I'm afraid this is a wontfix, sorry.
The SAFETY comments and lots of testing should suffice!

**Comment by GnomedDev** [comment]
As seen by #24, safety comments and testing without miri will not make unsafe magically safe. I'm preparing a PR to remove the trivial unsafe, is there an acceptable performance loss or must it be 1-1? @null8626.

**Comment by null8626** [comment]
Hmm, alright then, do as you please!

**Comment by null8626** [comment]
Hai! Any updates on this?

**Comment by null8626** [comment]
I've done some commits that removed some of the unsafe code! Let me know if there's anything you want to add!

**Comment by null8626** [comment]
Sooo i've removed all unsafe code in the Rust, WebAssembly, and Node.js crates today! Some unsafe still persists in the Java and C/C++ crates as they are a `cdylib` in nature.

Feel free to give me feedback on the current codebase! @GnomedDev @Milo123459

**Comment by Milo123459** [comment]
I think the next step would just be publishing a new release :)

**Comment by null8626** [comment]
A new release should be out later this month!

Thank you all for the advice! I will be more cautious with unsafe code. I apologize for closing this issue prematurely! :heart:

**Comment by null8626** [comment]
[The update is here!](https://github.com/null8626/decancer/releases/tag/v3.2.0)
