### ISSUE TITLE
`decancer` automatically lowercases all characters

### ISSUE THREAD

**Issue by net-tech** [null8626/decancer#23]
Hi there,

I'm experiencing an issue where `decancer` automatically lowercases all uppercase letters. As far as I understand, this is unintentional behavior (since it is not documented anywhere I looked). If it is intentional, could we have an option that keeps the case of non-violating characters?

### Issue Details
- `decancer` Version: 2.0.2
- macOS Version: 14.3.1
- Chip: Apple M2 Pro
- Architecture: arm64
- Node.js Version: v20.4.0
- Behavior: The package automatically converts all uppercase letters to lowercase.
- Expected Behavior: The case of non-violating characters should be preserved.

### Minimal Reproduction
```ts
import decancer from "decancer"

console.log(decancer("Test").toString()) // Expected output: "Test", actual output: "test"
console.log(decancer("TeSt").toString()) // Expected output: "TeSt", actual output: "test"
```

**Comment by null8626** [comment]
Hi! Yes, unfortunately this is an intentional design decision. All characters are lowercased in order to ease the comparison checks later.

**Comment by null8626** [comment]
May i ask why you would want this to be a feature? Because the purpose of the output of decancer is for comparison, not to display (it's NOT for formatting!)

**Comment by net-tech** [comment]
> May i ask why you would want this to be a feature?

I'm working on a Discord bot that cleans up the display names of members (You seem to be familiar with what Discord and its bots are) so I'm just trying to replace the characters that are strange.

I was originally using https://www.npmjs.com/package/@aero/sanitizer but `decancer` is more performant which is what attracted me to it.

**Comment by null8626** [comment]
Ah, i see, i could make a feature that lets you customize how the curing process works, though that would be breaking (for some bindings) therefore would be for a major update.

**Comment by net-tech** [comment]
I see. How would adjusting the curing process look like from a dev perspective?

**Comment by null8626** [comment]
Things like ```js
decancer(text, {
  retainCapitalization: true
})
```
or
```js
const config = decancer.config({
  retainCapitalization: true
})

decancer(text, config)
```

**Comment by net-tech** [comment]
Yeah that would be very nice

**Comment by null8626** [comment]
Please note that this change would be major and breaking (therefore for `v3.0.0`) - and such change would be time consuming. Be patient!

**Comment by net-tech** [comment]
No problem and thanks for your quick replies!

**Comment by null8626** [comment]
@net-tech Quick question regarding the ambiguity of capitalization: Some unicode characters, like 🆑 are shown in uppercase `CL`, do you think decancer should output them in uppercase as well? (Despite 🆑 technically being neither a lowercase nor uppercase character)

If yes, this can be ambiguous when the package says `retainCapitalization`.

**Comment by net-tech** [comment]
I would just keep it simple

**Comment by null8626** [comment]
Hai! By 19 February 2024, this issue has been resolved in the latest commit. At the moment you just need to wait until `v3.0.0` is out.

**Comment by null8626** [comment]
Thank you soo much for that offer! ❤️ I've never gotten a donation before -- i'm afraid at the moment **donation links won't be available until 22 April 2024**. I'll let you know once it's available!

**Comment by net-tech** [comment]
No problem. When it's available let me know via this issue or hello@nettech.dev. It will be a small amount but I'm still dedicated to giving something

**Comment by null8626** [comment]
It's finally here!

For your use case, it's probably either
```js
const output = decancer(string, {
  retainCapitalization: true
})
```
Or if you call `decancer()` multiple times, you can do
```js
const options = decancer.options({
  retainCapitalization: true
})

const output = decancer(string, options)
```
Or if you want for decancer to keep capitalization and not cure characters from the world's major foreign scripts, you can do
```js
// output is a javascript string
const output = decancer.format(string)
```

Cheers! If you have any problems or found any bugs, please be sure to let me know! Happy coding! Much love :heart::heart:

**Comment by net-tech** [comment]
Thank you so much!

**Comment by null8626** [comment]
:heart:

**Comment by null8626** [comment]
Hey @net-tech! Due to a slight hiccup in the `cure_char_inner` function, this bug apparently still persists by `v3.0.0`, i'm so sorry for this. 😭 This bug should be fixed by the [latest update, `v3.1.2`](https://github.com/null8626/decancer/releases/tag/v3.1.2)! :heart:

**Comment by net-tech** [comment]
> Hey @net-tech! Due to a slight hiccup in the `cure_char_inner` function, this bug apparently still persists for ASCII characters by `v3.0.0`, i'm so sorry for this. 😭 This bug should be fixed by the [latest update, `v3.1.2`](https://github.com/null8626/decancer/releases/tag/v3.1.2)! :heart:

No problem! Thanks for letting me know.

**Comment by null8626** [comment]
@net-tech Hai! You can now support me through donations at ko-fi. So sorry for the delay, setting it up took a while!

**Comment by net-tech** [comment]
Just donated! Thank you for setting it up and for fixing the issue!

**Comment by null8626** [comment]
Thank you so much for the donation! I'm glad that my project helped yours! :heart:
