### ISSUE TITLE
Undefined behavior in tests

### ISSUE THREAD

**Issue by GnomedDev** [null8626/decancer#24]
https://github.com/null8626/decancer/blob/3f4e7df432c111c3d4851d3db61ae0178182df9d/core/src/tests.rs#L233 This is always undefined behavior, as although not read it is still a value that is being created and passed to llvm as `noundef`. This will cause aborts in a couple Rust versions, when this pattern is compiled to `ud2` (undefined instruction, abort instantly).

This is already being caught by running `clippy` locally, which I suggest is added to CI, under the `clippy::uninit_assumed_init` lint.

**Comment by FlareFlo** [comment]
Running miri reports the following:
`MIRIFLAGS="-Zmiri-disable-isolation" cargo +nightly miri nextest run --test-threads 20`
```
--- STDERR:              decancer tests::isolating_run_sequences ---
error: Undefined Behavior: using uninitialized data, but this operation requires initialized memory
   --> src/tests.rs:233:14
    |
233 |       range: MaybeUninit::uninit().assume_init(),
    |              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ using uninitialized data, but this operation requires initialized memory
    |
    = help: this indicates a bug in the program: it performed an invalid operation, and caused Undefined Behavior
    = help: see https://doc.rust-lang.org/nightly/reference/behavior-considered-undefined.html for further information
    = note: BACKTRACE on thread `tests::isolatin`:
    = note: inside `tests::isolating_run_sequences` at src/tests.rs:233:14: 233:49
```

**Comment by null8626** [comment]
Hai! Thank you so much for this. :heart:

**Comment by null8626** [comment]
Fixed in https://github.com/null8626/decancer/commit/967467c55ad460b454e9a5338d8988ddcd91ecfb!
