### ISSUE TITLE
Support for Arabic

### ISSUE THREAD

**Issue by bacloud23** [null8626/decancer#25]
Hi,
I expect text of different languages, arabic included.
Take this sentence from https://ar.lipsum.com/

```js
import decancer from 'decancer'

const str = decancer('لا أحد يحب الألم بذاته، يسعى ورائه أو يبتغيه').toString()
console.log(str)
```

This gives a very scrambled text:

> oseتبs gi osijg seسs ,oتiذب مjiji بcs دci ij

Thank you for providing Decancer :)

**Comment by null8626** [comment]
Hai, @bacloud23!

You can customize decancer to avoid this issue.

```js
import decancer from 'decancer'

// this makes decancer not reorder the right-to-left arabic characters.
const str1 = decancer('لا أحد يحب الألم بذاته، يسعى ورائه أو يبتغيه', {
  disableBidi: true
})

// this makes decancer not cure arabic characters
const str2 = decancer('لا أحد يحب الألم بذاته، يسعى ورائه أو يبتغيه', {
  retainArabic: true
})
// settings can be combined.

// settings can also be stored as a constant
const settings = decancer.options({
  retainArabic: true,
  disableBidi: true
})

const str3 = decancer('لا أحد يحب الألم بذاته، يسعى ورائه أو يبتغيه', settings)
```

**Comment by null8626** [comment]
Also, as a heads up, i do not recommend using `.toString()` at the output if you want to compare it with other strings -- decancer already has its own special comparison methods that outrival the JavaScript ones!

**Comment by bacloud23** [comment]
Hi @null8626 ,
Thank you for the quick response :)

It work !

What about `.toString()` ? I understand that *decancer* may have other uses, but I'm simply curing use provided text, which might be scrambled due to copy paste , outdated browsers / clients, or any other encoding errors, so that at the end, back in the database I cure all received text.

Is it still fine to use `.toString()` for this ?

**Comment by null8626** [comment]
@bacloud23 

While it's not what decancer was originally intended for (it was initially intended for comparing with other strings hahaha) sure, you can use it :)

Just note that decancer can make false-positive translations :)

**Comment by bacloud23** [comment]
Understood. Thanks a lot for explanations.
