### ISSUE TITLE
[java] Migrate from Jitpack

### ISSUE THREAD

**Issue by null8626** [null8626/decancer#27]
As of version v3.2.0, i've noticed that Jitpack no longer allows newer releases of the Java binding of decancer due to the repository's history exceeding 500 MB.

Therefore, i am currently in the process of migrating from jitpack to another host! Sadly, this may delay future releases.

**Comment by prouzpe3** [comment]
Not sure what #help-wanted means, but have you tried following this blog post about publishing to maven central? https://medium.com/@efthymiou.dimitrios1/how-to-publish-your-library-to-maven-central-3923139967e1

**Comment by null8626** [comment]
Thank you so much for this! Will take a look into it later.

**Comment by prouzpe3** [comment]
@null8626 Could you please let me know when you expect it to be completed? If there's anything I can do to assist, please let me know.

**Comment by null8626** [comment]
I am still working on it today! Please be patient. Expect it to be done around this or next week.

**Comment by null8626** [comment]
Hai, @prouzpe3! This issue can now be closed with the [latest release](https://github.com/null8626/decancer/releases/tag/v3.2.2).
