### ISSUE TITLE
Support for Turkish characters

### ISSUE THREAD

**Issue by Triggered0** [null8626/decancer#28]
I couldn't find an option to retain Turkish characters
`ğ ü ş i ö ç Ğ Ü Ş İ Ö Ç`
Can you add a support for that please?

**Comment by null8626** [comment]
Hai! Have you tried `retain_diacritics()` or `retainDiacritics`?

**Comment by Triggered0** [comment]
I have tried it. It works but if u can add an option to only retain those characters i will be gratefull

**Comment by null8626** [comment]
Done! Should be resolved by v3.2.4!
