### ISSUE TITLE
`cure` hangs when fed specific character

### ISSUE THREAD

**Issue by virtualritz** [null8626/decancer#4]
I.e. when fed unicode character “ˑ” (U+02D1)  (Modifier Letter Half Triangular Colon):
```rust
fn main() {
    println!("{}", decancer::cure("ˑ").as_str());
    println!("This never prints.");
}
```

**Comment by virtualritz** [comment]
FYI: I am using this for string matching to find unicode glyphs.
Because of this I'm building a lookup table where for each unicode character I have the decancered version.

P.S.P It would be great if there was a version of `cure` that takes a single `char` and spits out a `char` (or `u32`).

**Comment by null8626** [comment]
thanks for this bug report! will look into later.

**Comment by null8626** [comment]
apparently, the bug is in the binary search implementation... i've recently fixed the problem and added several more confusables (including the one you've pointed out)

the changes should be included in a future update (v1.5.4) in a few days. be patient!

**Comment by virtualritz** [comment]
Cheers!
I this alreay in the repo so I can use an overlay in my `Cargo.toml`?

**Comment by null8626** [comment]
i've fixed the issue in a commit 2 days ago - currently adding more features to version `1.5.4`.

sorry if it takes a while - i'm very busy!

**Comment by null8626** [comment]
[`v1.5.4` is here!](https://github.com/null8626/decancer/releases/v1.5.4)
